### ISSUE TITLE
INT signal is trapped away from spawned process

### ISSUE THREAD

**Issue by dandv** [fir3pho3nixx/grunt-spawn#6]
Steps to reproduce:

```sh
git clone git@github.com:MeteorPackaging/summernote.git
cd summernote
git checkout meteor-integration
npm install
grunt meteor-test
```

This uses `grunt-spawn` (replace "shell" in the [source lines](https://github.com/MeteorPackaging/summernote/blob/meteor-integration/Gruntfile.js#L109-117)) to execute `meteor/runtests/sh`, which [traps the INT signal](https://github.com/MeteorPackaging/summernote/blob/meteor-integration/meteor/runtests.sh#L11-16).

Now press Ctrl+C.

Notice that grunt aborts instantly, without giving `runtests.sh` a chance to trap the INT signal and do its cleanup.

**Comment by fir3pho3nixx** [comment]
Readers, please see "INT signal is trapped away from spawned process". This is an issue on a completely different framework. grunt-spawn has inevitably evolved to using grunt.util.spawn naturally. It never used to. 

This issue has highlighted that documentation *again* needs to be updated. 

Will leave this open, until I have feedback on the merge request. 

https://github.com/MeteorPackaging/mousetrap/pull/1

**Comment by fir3pho3nixx** [comment]
Remember failed return codes(>0), will fail grunt-spawn.
