### ISSUE TITLE
Package.json Dependencies need to be set

### ISSUE THREAD

**Issue by NoRKin** [fir3pho3nixx/grunt-spawn#7]
Hi there,

I tried to install grunt-spawn today but I couldn't make it work due to dependencies that have been recently updated and that have breaking changes.

I could make it work specifying. lodash 2.4.1 and string-format: 0.2.1

**Comment by fir3pho3nixx** [comment]
What is the error you are getting? Could you post a sample of how it is breaking?

**Comment by fir3pho3nixx** [comment]
Found the problem after I wiped node_modules and started afresh. _([1,2,3]).each(...) in loads does not appear to be same as _.each([1,2,3], ...)???

I will raise this with them and see what they say. Thanks for reporting.

**Comment by fir3pho3nixx** [comment]
Follow Up: https://github.com/lodash/lodash/issues/1040
